### ISSUE TITLE
Step5: 商品タグを1行ずつ表記せよ！

### ISSUE THREAD

**Issue by gen0e0** [hodoyoi/typescript-tutorial-for-beginners#1]
<img width="368" alt="スクリーンショット 2020-05-15 9 45 28" src="https://user-images.githubusercontent.com/576256/81999690-d585e380-9690-11ea-91ec-bbc74acd3cf9.png">

タグの切れ目がないので視認性にイチャモンがあります  

tagをループして`<div></div>`で囲えませんか？

**Comment by rakisuta-bun** [comment]
ブランチ切って何故かpushできない問題を抱えました。
なおtagをループして<div></div>で囲えませんか？は未解決
