### ISSUE TITLE
勝利画像を付けましょう

### ISSUE THREAD

**Issue by gen0e0** [hodoyoi/typescript-tutorial-for-beginners#11]
人間は勝つとアドレナリンが分泌されて非常に嬉しいので、勝った時の画像をより刺激的なものにしましょう

例
[https://www.irasutoya.com/2015/09/blog-post_80.html](https://www.irasutoya.com/2015/09/blog-post_80.html)
[https://www.irasutoya.com/2018/10/blog-post_254.html](https://www.irasutoya.com/2018/10/blog-post_254.html)

**Comment by gen0e0** [comment]
参考 負け画像
[https://www.irasutoya.com/2015/09/blog-post_7.html](https://www.irasutoya.com/2015/09/blog-post_7.html)

**Comment by rakisuta-bun** [comment]
fix #11
