### ISSUE TITLE
bootstrapのグリッドシステムが効かない問題

### ISSUE THREAD

**Issue by rakisuta-bun** [hodoyoi/typescript-tutorial-for-beginners#22]
col-6 col-md-3と指定した場合
画面表示が小さい時　col-6で表示したい
画面が大きい時は　col-md-3で表示したい。
現在は画面の大きさに関わらずcol-md-3が適用されてしまう問題
なおboosstrapvueにて
b-col cols="6" md="3"
この指定でもmd-3が小さい画面でも適用されてしまう

**Comment by gen0e0** [comment]
index.htmlのheadタグ内に
`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`
をいれてください

**Comment by rakisuta-bun** [comment]
headに
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
これで一件落着
