### ISSUE TITLE
フッターがいい感じにならない問題

### ISSUE THREAD

**Issue by rakisuta-bun** [hodoyoi/typescript-tutorial-for-beginners#24]
フッターがかなり粗悪なのがしんどくて吐きそう

**Comment by gen0e0** [comment]
<img width="1407" alt="スクリーンショット 2020-06-01 11 46 50" src="https://user-images.githubusercontent.com/576256/83371753-561d4180-a3fe-11ea-81f8-1fb909dce220.png">
Macのすスクショ機能（Cmd+Shift+4）は、コメントが入れられるのでこゆの書いて欲しい

**Comment by rakisuta-bun** [comment]
まさにこれが理想の形です
いつもながら説明下手で申し訳ない

**Comment by gen0e0** [comment]
https://cccabinet.jpn.org/bootstrap4/sample/sticky-footer

**Comment by gen0e0** [comment]
実装手順
・html, bodyに`height: 100%`のスタイルシートを適用する（bootstrapの場合だとh-100クラスをつける）
・bodyに `display:flex` と `flex-direction: column` を適用する（bootstrapだとd-flexとflex-columnクラス）
・フッターの要素に `margin-top: auto` を適用する （bootstrapだとmt-auto）

**Comment by gen0e0** [comment]
ヒントとりあえずここまで

**Comment by rakisuta-bun** [comment]
fix
