### ISSUE TITLE
Step6: Vue.js 入門

### ISSUE THREAD

**Issue by gen0e0** [hodoyoi/typescript-tutorial-for-beginners#4]
新しいライブラリを追加したので、問題を解く前に `yarn` でパッケージをインストールしてください

**Comment by gen0e0** [comment]
Visual Studio CodeのVeturプラグインを入れると、`.vue`ファイルがうまくシンタックスハイライトされるので、よかったらインストールしてください

**Comment by gen0e0** [comment]
https://marketplace.visualstudio.com/items?itemName=octref.vetur

**Comment by rakisuta-bun** [comment]
インストールOK!

**Comment by rakisuta-bun** [comment]
Vue.js神がかってるかも
