### ISSUE TITLE
じゃんけんを3回以上続けたらグーチョキパーボタンが現れて必勝になって欲しい

### ISSUE THREAD

**Issue by gen0e0** [hodoyoi/typescript-tutorial-for-beginners#5]
昨今の軟弱ユーザーのUXを上げるため以下の機能を実装せよ

・じゃんけんを一回やったらjankenCountを1ふやす
・グーチョキパーボタンを出せるかどうか（3回以上プレイ）の判定を入れる
・グーチョキパーボタンを押した時の勝利判定を入れる

**Comment by gen0e0** [comment]
・グーチョキパーボタンを押したら、相手がなんの手だろうと必勝になる

**Comment by rakisuta-bun** [comment]
最強は猫
