### ISSUE TITLE
じゃんけんの手が視覚的に分かりづらいのでクソでかい絵文字を表示させてください

### ISSUE THREAD

**Issue by gen0e0** [hodoyoi/typescript-tutorial-for-beginners#6]
日本語のグーチョキパーが難しくて読めないユーザーがおりUXを著しく下げていますので、「グー」と同時に✊みたいなクソデカ絵文字を表記させてください
プレイヤーとCPUの手、2つ分おねがいします　これで救える命があります

**Comment by rakisuta-bun** [comment]
命は救われたのだ
