### ISSUE TITLE
猫のエネルギーが溜まっている事を視覚的に分かりやすくしてください

### ISSUE THREAD

**Issue by gen0e0** [hodoyoi/typescript-tutorial-for-beginners#8]
このままでは猫がいつ使えるのかプレイヤーがわからず、オタクの誹謗中傷の的になってしまいます。
猫が使用可能である事を伝えるため、カウントの代わりに、以下のように猫エネルギーが溜まっている事を表現してください

猫エネルギー0の場合
🐱：☆☆☆
猫エネルギー1の場合
🐱：★☆☆
猫エネルギー2の場合
🐱：★★☆
猫エネルギー3以上の場合
🐱：★★★ [!!!CAT POWER MAX!!!]

**Comment by rakisuta-bun** [comment]
できた
